### ISSUE TITLE
Can't run tests with this plugin

### ISSUE THREAD

**Issue by servarius** [astraw38/pytest-docgen#3]
Hi!

By running tests with required argument --rst-dir=_docs got this :

`============================= test session starts ==============================
platform darwin -- Python 3.8.1, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /.../venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/gpbu8490/Documents/Code/dataopstools
plugins: requests-mock-1.7.0, mock-2.0.0, docgen-1.1.1, allure-pytest-2.8.7, cov-2.8.1
collecting ... collected 10 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 193, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 236, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 83, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 246, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 441, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 83, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/../venv/lib/python3.8/site-packages/pytest_docgen/pytest_docgen.py", line 502, in pytest_collection_modifyitems
INTERNALERROR>     test_doccol = NodeDocCollector(node_name=test.name,
INTERNALERROR>   File "/Users/../venv/lib/python3.8/site-packages/pytest_docgen/pytest_docgen.py", line 86, in __init__
INTERNALERROR>     cut_dir = pytest.config.getoption("rst_cut_dir")
INTERNALERROR> AttributeError: module 'pytest' has no attribute 'config'`

conftest.py looks like:

`import pytest
pytest_plugins = ["pytest_docgen"]`

index.rst, conf.py for sphinx and tests directory provided.

**Comment by astraw38** [comment]
Thanks for the report -- i've not had a chance to update this for pytest versions 4+. I'll see what I can do for you.

**Comment by servarius** [comment]
> Thanks for the report -- i've not had a chance to update this for pytest versions 4+. I'll see what I can do for you.

Thank you! Last build generates documentation successfully.
